### ISSUE TITLE
Audio file is not playing while the call | Possibillity to record

### ISSUE THREAD

**Issue by JackOman69** [moha-abdi/PySIP#2]
Thank you very much for your work on this repo!!

Here is my code:

```
import asyncio
from PySIP.call import VOIP
import soundfile as sf

async def main():
    voip = VOIP(username='858384538583845', route='server:port', password='fddsd')

    text = "Hello, this is I'm yours best friend in the world"

    await voip.call('79263611985', tts=True, text=text)
    
    # Store the conversation in a .wav file
    # wav_filename = 'conversation.wav'
    # sf.write(wav_filename, conversation, voip.sample_rate)
    
if __name__ == "__main__":
    asyncio.run(main())
```

While answering the call from SIP server, there's no any sound from the caller, even if I try to pass the audio file in .wav format

Also I have a question, if there's any implementation of recording the conversation?
If you have any ideas on it, I'll be very glad to hear you!

**Comment by moha-abdi** [comment]
Hello, for the audio not playing, currently I only added PCMA codecs, but I will add PCMU and other codecs for the coming days as they just require a little bit of work, and for the recording I already added it. I  just did not pull it, I will do that very soon aswell. If you have any other issues feel free to report them. PRs will also be appreciated. thanks/.

**Comment by moha-abdi** [comment]
Hello, added PCAMA codes which will most likely fix the audio issue, also added the audio recording. Please check #3 for more info thanks.
